url: "http://ocmock.org"
highlighter: rouge
exclude: [Gemfile, Gemfile.lock, Makefile, run.sh]
permalink: pretty
date_format: "%d %B %Y"
baseurl: "https://ocmock.org"
quvynurl: "https://www.mulle-kybernetik.com/quvyn-ocmock"
